package com.pradeep_test.pub_bzs_cns_all_bre_panelist_rule_edit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_dml implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_dml() {
    }




}